### ISSUE TITLE
plugin not appearing in 1.79

### ISSUE THREAD

**Issue by lgwapnitsky** [versvs/ttrss2scuttle#4]
i moved the semanticscuttle folder under the plugins and it's not showing in the config menu.

**Comment by versvs** [comment]
Hi igwapnitsky,

thanks for your feedback. I've been unable to adapt the plugin to the latest tt-rss version, even though I know the compatibility has been decreasing since 1.7.5 (where first issues appeared).

I promise to get it back on track this week.

Thanks again!

**Comment by greencrab** [comment]
I fixed the problem for the plugin in v1.8, but don't have v1.79 to test.  I also use the original scuttle instead of semanticscuttle, but it seem to work just the same.  I'll send a pull request.

**Comment by versvs** [comment]
Kudos for you, greencrab.

Since upgrading TT-RSS to version 1.8 should not be an issue (server requirements stay still, so if you have 1.7.9 running, chances are you can upgrade to 1.8 within a couple of minutes) I dont think it is strictly necessary to branch out a fix for 1.7.9 now that greencrab helped us getting it up-to-date for 1.8.

If upgrading really is a problem for you, please reopen the issue and I'll try to look at the problem.
